# Generated by Django 4.0.5 on 2024-04-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=40)),
                ('salon_email', models.EmailField(max_length=40, unique=True)),
                ('salon_location', models.CharField(default='', max_length=100)),
                ('salon_profile_pic', models.ImageField(default='', max_length=255, upload_to='profile')),
                ('password', models.TextField()),
            ],
        ),
    ]
