# Generated by Django 4.0.5 on 2024-04-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='salon_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='business',
            name='salon_location',
            field=models.CharField(default='19.758381:74.474215', max_length=100),
        ),
    ]
