# Generated by Django 4.0.5 on 2024-04-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_business_salon_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=40, unique=True)),
                ('user_mobile', models.IntegerField()),
                ('user_profile_pic', models.ImageField(default='', max_length=255, upload_to='user/profile')),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='salon_profile_pic',
            field=models.ImageField(default='', max_length=255, upload_to='business/profile'),
        ),
    ]
