# Generated by Django 4.0.5 on 2024-04-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_user_alter_business_salon_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('service_image', models.ImageField(default='', max_length=255, upload_to='service')),
            ],
        ),
    ]
