# Generated by Django 4.0.5 on 2024-04-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_image',
        ),
        migrations.AddField(
            model_name='services',
            name='service_icon',
            field=models.ImageField(default='', max_length=255, upload_to='service/icon'),
        ),
    ]
