# Generated by Django 4.0.5 on 2024-04-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_remove_services_service_image_services_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servies_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(default='', max_length=255, upload_to='service/image')),
                ('service_cost', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.business')),
            ],
            options={
                'unique_together': {('service_type_name', 'business')},
            },
        ),
    ]
