# Generated by Django 4.0.5 on 2024-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_servies_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='open_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
