# Generated by Django 4.0.5 on 2024-04-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_servies_types_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servies_types',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.services'),
        ),
    ]
