# Generated by Django 4.0.5 on 2024-04-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_servies_types_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='salon_owner_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
