# Generated by Django 4.0.5 on 2024-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_alter_business_salon_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='salon_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
