# Generated by Django 4.0.5 on 2024-04-25 12:16

from django.db import migrations, models
import django.db.models.deletion
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_alter_business_salon_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancel', 'cancel')], default='pending', max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_creation_date', models.DateField(default=salon.models.get_today_date)),
                ('appointment_start_time', models.TimeField()),
                ('appointment_end_time', models.TimeField()),
                ('appointment_cancellation_reason', models.TextField(blank=True, default=None, null=True)),
                ('Salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.user')),
            ],
        ),
    ]
