# Generated by Django 4.0.5 on 2024-04-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Salon',
            new_name='salon',
        ),
    ]
