# Generated by Django 4.0.4 on 2022-05-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('mnumber', models.CharField(max_length=12)),
                ('Comment', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
