# Generated by Django 4.0.4 on 2022-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
