# Generated by Django 4.0.4 on 2022-05-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userlogin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='businesslogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=150)),
                ('bname', models.CharField(max_length=150)),
                ('bemail', models.CharField(max_length=100)),
                ('baddr', models.TextField()),
                ('buname', models.CharField(max_length=20)),
                ('bpwd', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
