# Generated by Django 4.0.4 on 2022-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_businesslogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='addplanfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=150)),
                ('cpweek', models.IntegerField()),
                ('mealtype', models.CharField(max_length=20)),
                ('buname', models.CharField(max_length=20)),
                ('sunday_meal', models.TextField()),
                ('monday_meal', models.TextField()),
                ('tuesday_meal', models.TextField()),
                ('wednesday_meal', models.TextField()),
                ('thursday_meal', models.TextField()),
                ('friday_meal', models.TextField()),
                ('saturday_meal', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
