# Generated by Django 4.0.4 on 2022-05-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bookplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookplan',
        ),
    ]
