# Generated by Django 4.0.4 on 2022-05-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bookplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookplan',
            new_name='bookplane',
        ),
    ]
