# Generated by Django 4.0.4 on 2022-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_bookplane_p_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookplane',
            name='p_end',
            field=models.DateField(),
        ),
    ]
