# Generated by Django 4.0.4 on 2022-05-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_bookplane_p_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookplane',
        ),
    ]
