# Generated by Django 4.0.4 on 2022-05-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payments',
            new_name='payment',
        ),
    ]
