# Generated by Django 4.0.4 on 2022-05-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_payments_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='paymentz',
        ),
    ]
